apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dGVzdA==
  POSTGRES_PASSWORD: dGVzdA==
  POSTGRES_DB: dGVzdF9kYg==
stringData:
  DATABASE_URL: "postgresql://test:test@postgres-service:5432/test_db"